apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: local.ecosia.org/tree
      http:
        paths:
          - path: /tree
            pathType: Prefix
            backend:
              service:
                name: flask-service
                port:
                  number: 80
